### ISSUE TITLE
Unable to open DMs/Messages

### ISSUE THREAD

**Issue by tcspears** [holium/realm-support#27] opened 2023-01-25 21:54 UTC
Anytime I click on the DMs/messages icon in the bottom right hand corner of Realm, Realm's desktop goes blank and I get a message that reads: I'm still getting a 'Something went wrong' error. I can only recover from the error by exiting out of Realm and restarting it. I've reproduced this on a second ship of mine, so it's not unique to my ship.

Screenshot of error message is below:
![Screenshot 2023-01-25 at 21 51 18](https://user-images.githubusercontent.com/3354679/214699693-49e280bd-14a4-472a-9382-4033ad618ded.png)

**Comment by drunkplato** [comment] 2023-01-31 14:39
This is an issue with ContactRow, I wonder if it has to do with %landscape being suspended? Can you check `+vat %landscape`?

**Comment by tcspears** [comment] 2023-01-31 14:43
![Screenshot 2023-01-31 at 14 42 14](https://user-images.githubusercontent.com/3354679/215791647-ca3a403c-1f15-4c83-b2f2-1adf02801c31.png)

**Comment by drunkplato** [comment] 2023-01-31 15:52
I can look into the `ContactRow` component and check what may be causing the issue.

**Comment by tcspears** [comment] 2023-02-04 08:44
The issue is persisting with the latest runtime (v1.18) and base update (6dufe).

**Comment by gdbroman** [comment] 2023-02-13 17:21
Hey @tcspears thanks for reporting this. A fix has been merged and will go out in the next release after 0.4.0. Would be splendid if you could confirm that the issue is fixed once that's out.

**Comment by tcspears** [comment] 2023-02-22 09:54
Great, looking forward to the next update.

**Comment by tcspears** [comment] 2023-02-28 15:58
@gdbroman - I'm still having this same problem (running 0.5.1-hotfix (0.5.1-hotfix))

**Comment by tcspears** [comment] 2023-03-01 13:23
@gdbroman - I've reproduced this error now on three different planets. The only thing I can think of that these three planets have in common is:
1. I used the same Realm invite code to set up Realm on each
2. They have a similar hosting setup (Oracle VPSs using reverse proxy via Caddy)

I don't think (2) is the issue - I've talked to another person who uses a similar hosting setup and they aren't experiencing this problem. Could the issue be (1)?

**Comment by tcspears** [comment] 2023-03-02 09:29
No, nothing jumps out. One of the ships is barely used. Has nobody else reported this issue?

**Comment by tcspears** [comment] 2023-03-02 14:42
Does Realm attempt to use any ports besides https to access the ship? Could this be a firewall issue?

**Comment by gdbroman** [comment] 2023-03-02 14:54
> Does Realm attempt to use any ports besides https to access the ship? Could this be a firewall issue?

We have had issues with VPNs, you could try disabling it if you have one @tcspears

**Comment by tcspears** [comment] 2023-03-02 15:15
I'm trying this but my invite code is no longer working, so I can't move forward. Do you guys disable codes that have been used too many times? (I've needed to reinstall Realm multiple times to try to fix this).

**Comment by gdbroman** [comment] 2023-03-02 15:24
Ah I see, I've asked Cody to reach out to you, you should get an email at mailto:tcs@tcspears.net soon

**Comment by tcspears** [comment] 2023-03-09 16:58
@gdbroman: I was ultimately able to resolve this problem, but only by breaching my ship and installing Realm from a freshly booted identity (via Arvo v1.22). Perhaps there was some cruft in my ship left over from the Groups 1 to Groups 2 migration that was preventing ContactRow from working properly.

**Comment by ajlamarc** [comment] 2023-05-27 18:09
Closing due to rebuilt chat being launched since

**Closed by ajlamarc** 2023-05-27 18:09 UTC
